-- Famora — RLS bootstrap (migration 0001)
-- ============================================
-- Applies AFTER Prisma generated the schema (tables, enums, columns). Run with:
--   supabase db push  |  psql "…" -f supabase/migrations/0001_enable_rls.sql
--
-- Security model
-- --------------
--  • RLS is the database floor (least privilege). The authoritative layer is
--    the application server (src/lib/authorization: hasPermission +
--    FamilyGrant merges). Policies here are deliberately conservative and may
--    NOT re-implement every FamilyGrant rule — they only guarantee a safe
--    minimum: nobody outside the family, no inactive member, no raw exposure
--    of Hidden Admin (§43.16–§43.24).
--  • Column names are camelCase exactly as generated by Prisma
--    (e.g. "familyId", "userId", "internalRole") — they MUST be double-quoted
--    in SQL. Table & enum names are snake_case (`@@map`).
--  • Hidden Admin rows (family_members / family_whitelist) are only readable
--    by a Hidden Admin viewer. No other role can observe them — even raw SQL
--    is blocked by policy (§43.18 no detectability).

-- ---------------------------------------------------------------------------
-- 1. Helper functions (security definer, no RLS recursion)
-- ---------------------------------------------------------------------------

create or replace function public.famora_auth_uid() returns uuid
language sql stable security definer set search_path = public, pg_temp
as $$
  select auth.uid();
$$;

create or replace function public.famora_is_active_member("pFamilyId" uuid) returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.family_members fm
    where fm."userId" = public.famora_auth_uid()
      and fm."familyId" = "pFamilyId"
      and fm.status = 'ACTIVE'
  );
$$;

create or replace function public.famora_has_internal_role("pFamilyId" uuid, "pRoles" internal_role[]) returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.family_members fm
    where fm."userId" = public.famora_auth_uid()
      and fm."familyId" = "pFamilyId"
      and fm.status = 'ACTIVE'
      and fm."internalRole" = any("pRoles")
  );
$$;

-- Viewer is an active member of at least one family that the target member belongs to.
create or replace function public.famora_can_see_member("pUserId" uuid) returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.family_members viewer
    where viewer."userId" = public.famora_auth_uid()
      and viewer.status = 'ACTIVE'
      and exists (
        select 1
        from public.family_members target
        where target."userId" = "pUserId"
          and target."familyId" = viewer."familyId"
          and target.status = 'ACTIVE'
      )
  );
$$;

-- Viewer sees Hidden Admin rows only when the viewer is a Hidden Admin (§43.18).
create or replace function public.famora_may_view_hidden_admin("pFamilyId" uuid) returns boolean
language sql stable security definer set search_path = public, pg_temp
as $$
  select public.famora_has_internal_role("pFamilyId", array['HIDDEN_ADMIN']::internal_role[]);
$$;

-- ---------------------------------------------------------------------------
-- 2. Enable RLS on every table (Prisma-created). Idempotent.
-- ---------------------------------------------------------------------------

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'users','user_settings','user_devices',
    'families','family_settings','family_features',
    'family_members','family_member_settings','family_grants','family_whitelist',
    'permissions','role_permissions',
    'conversations','conversation_members','messages','message_edits',
    'message_attachments','message_reactions','message_read_states',
    'saved_messages','pinned_messages',
    'polls','poll_options','poll_votes',
    'event_categories','calendar_events','event_attendees','event_reminders',
    'tasks','task_assignments','task_comments','task_history',
    'notebooks','notebook_pages','notebook_page_versions','shared_page_grants','page_tags',
    'file_blobs','folders','files',
    'announcements','announcement_reads',
    'family_contacts','recipes','recipe_comments',
    'albums','memories','memory_assets','memory_comments','memory_reactions',
    'notifications','user_notification_preferences',
    'audit_logs','activity_events'
  ] loop
    execute format('alter table public.%I enable row level security;', tbl);
  end loop;
end
$$;

-- ---------------------------------------------------------------------------
-- 3. Policies — core taxonomy & identity
-- ---------------------------------------------------------------------------

-- users: readable by any member of a shared family; a user may update self.
drop policy if exists "users_select_members" on public.users;
create policy "users_select_members" on public.users
  for select using (public.famora_can_see_member(public.users.id));

drop policy if exists "users_update_self" on public.users;
create policy "users_update_self" on public.users
  for update using (public.users.id = public.famora_auth_uid())
  with check (public.users.id = public.famora_auth_uid());

-- user_settings / user_devices: owner only.
drop policy if exists "user_settings_owner" on public.user_settings;
create policy "user_settings_owner" on public.user_settings
  using (public.user_settings."userId" = public.famora_auth_uid());

drop policy if exists "user_devices_owner" on public.user_devices;
create policy "user_devices_owner" on public.user_devices
  using (public.user_devices."userId" = public.famora_auth_uid());

-- ---------------------------------------------------------------------------
-- 4. Families & membership
-- ---------------------------------------------------------------------------

drop policy if exists "families_select_members" on public.families;
create policy "families_select_members" on public.families
  for select using (public.famora_is_active_member(public.families.id));

drop policy if exists "families_update_manage" on public.families;
create policy "families_update_manage" on public.families
  for update using (public.famora_has_internal_role(public.families.id, array['FAMILY_CHIEF','CO_FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[]))
  with check (public.famora_has_internal_role(public.families.id, array['FAMILY_CHIEF','CO_FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[]));

drop policy if exists "family_settings_select_members" on public.family_settings;
create policy "family_settings_select_members" on public.family_settings
  for select using (public.famora_is_active_member(public.family_settings."familyId"));

drop policy if exists "family_settings_update_manage" on public.family_settings;
create policy "family_settings_update_manage" on public.family_settings
  for update using (public.famora_has_internal_role(public.family_settings."familyId", array['FAMILY_CHIEF','CO_FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[]))
  with check (public.famora_has_internal_role(public.family_settings."familyId", array['FAMILY_CHIEF','CO_FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[]));

drop policy if exists "family_features_select_members" on public.family_features;
create policy "family_features_select_members" on public.family_features
  for select using (public.famora_is_active_member(public.family_features."familyId"));

drop policy if exists "family_features_update_manage" on public.family_features;
create policy "family_features_update_manage" on public.family_features
  for update using (public.famora_has_internal_role(public.family_features."familyId", array['FAMILY_CHIEF','CO_FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[]))
  with check (public.famora_has_internal_role(public.family_features."familyId", array['FAMILY_CHIEF','CO_FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[]));

-- family_members
--   select: same-family active viewer; Hidden Admin rows invisible to everyone
--   except Hidden Admin viewers (§43.18). No insert through the API — members
--   are created by the server only. Chief may update roles/status within family.
drop policy if exists "family_members_select_masked" on public.family_members;
create policy "family_members_select_masked" on public.family_members
  for select using (
    public.famora_is_active_member(public.family_members."familyId")
    and (
      public.family_members."internalRole" <> 'HIDDEN_ADMIN'::internal_role
      or public.famora_may_view_hidden_admin(public.family_members."familyId")
    )
  );

drop policy if exists "family_members_update_manage" on public.family_members;
create policy "family_members_update_manage" on public.family_members
  for update using (
    public.famora_has_internal_role(public.family_members."familyId", array['FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[])
    and public.family_members."internalRole" <> 'HIDDEN_ADMIN'::internal_role
  )
  with check (
    public.famora_has_internal_role(public.family_members."familyId", array['FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[])
    and public.family_members."internalRole" <> 'HIDDEN_ADMIN'::internal_role
  );

drop policy if exists "family_member_settings_own" on public.family_member_settings;
create policy "family_member_settings_own" on public.family_member_settings
  using (
    exists (
      select 1 from public.family_members fm
      where fm.id = public.family_member_settings."memberId"
        and fm."userId" = public.famora_auth_uid()
        and fm.status = 'ACTIVE'
    )
  );

-- family_whitelist: admin-only surface. Hidden Admin whitelist rows are masked.
drop policy if exists "family_whitelist_select_admins" on public.family_whitelist;
create policy "family_whitelist_select_admins" on public.family_whitelist
  for select using (
    public.famora_has_internal_role(public.family_whitelist."familyId", array['FAMILY_CHIEF','CO_FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[])
    and (
      public.family_whitelist."internalRole" <> 'HIDDEN_ADMIN'::internal_role
      or public.famora_may_view_hidden_admin(public.family_whitelist."familyId")
    )
  );

drop policy if exists "family_whitelist_write_chiefs" on public.family_whitelist;
create policy "family_whitelist_write_chiefs" on public.family_whitelist
  for insert with check (
    public.famora_has_internal_role(public.family_whitelist."familyId", array['FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[])
    and public.family_whitelist."internalRole" <> 'HIDDEN_ADMIN'::internal_role
  );

drop policy if exists "family_whitelist_delete_chiefs" on public.family_whitelist;
create policy "family_whitelist_delete_chiefs" on public.family_whitelist
  for delete using (
    public.famora_has_internal_role(public.family_whitelist."familyId", array['FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[])
    and public.family_whitelist."internalRole" <> 'HIDDEN_ADMIN'::internal_role
  );

-- family_grants: same-family members may read; chiefs write (server also guards).
drop policy if exists "family_grants_select_members" on public.family_grants;
create policy "family_grants_select_members" on public.family_grants
  for select using (public.famora_is_active_member(public.family_grants."familyId"));

drop policy if exists "family_grants_write_chiefs" on public.family_grants;
create policy "family_grants_write_chiefs" on public.family_grants
  for insert with check (public.famora_has_internal_role(public.family_grants."familyId", array['FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[]));

drop policy if exists "family_grants_delete_chiefs" on public.family_grants;
create policy "family_grants_delete_chiefs" on public.family_grants
  for delete using (public.famora_has_internal_role(public.family_grants."familyId", array['FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[]));

-- ---------------------------------------------------------------------------
-- 5. Permissions registry (read-only to everyone; writes are server-side only)
-- ---------------------------------------------------------------------------

drop policy if exists "permissions_select" on public.permissions;
create policy "permissions_select" on public.permissions for select using (true);

drop policy if exists "role_permissions_select" on public.role_permissions;
create policy "role_permissions_select" on public.role_permissions for select using (true);

-- ---------------------------------------------------------------------------
-- 6. Chat
-- ---------------------------------------------------------------------------

-- conversation access is derived from conversation_members (private per family).
drop policy if exists "conversations_select_members" on public.conversations;
create policy "conversations_select_members" on public.conversations
  for select using (
    exists (
      select 1
      from public.conversation_members cm
      join public.family_members fm on fm.id = cm."memberId"
      where cm."conversationId" = public.conversations.id
        and fm."userId" = public.famora_auth_uid()
        and fm.status = 'ACTIVE'
    )
  );

drop policy if exists "conversation_members_select_self" on public.conversation_members;
create policy "conversation_members_select_self" on public.conversation_members
  for select using (
    exists (
      select 1
      from public.family_members fm
      where fm.id = public.conversation_members."memberId"
        and fm."userId" = public.famora_auth_uid()
        and fm.status = 'ACTIVE'
    )
  );

drop policy if exists "messages_select_participant" on public.messages;
create policy "messages_select_participant" on public.messages
  for select using (
    public.messages."deletedAt" is null
    and exists (
      select 1
      from public.conversation_members cm
      join public.family_members fm on fm.id = cm."memberId"
      where cm."conversationId" = public.messages."conversationId"
        and fm."userId" = public.famora_auth_uid()
        and fm.status = 'ACTIVE'
    )
  );

drop policy if exists "messages_insert_send" on public.messages;
create policy "messages_insert_send" on public.messages
  for insert with check (
    exists (
      select 1
      from public.conversation_members cm
      join public.family_members fm on fm.id = cm."memberId"
      where cm."conversationId" = public.messages."conversationId"
        and fm."userId" = public.famora_auth_uid()
        and fm.status = 'ACTIVE'
    )
    and public.messages."senderMemberId" in (
      select id from public.family_members fm2
      where fm2."userId" = public.famora_auth_uid() and fm2.status = 'ACTIVE'
    )
  );

-- edit own message; moderators may delete any (soft).
drop policy if exists "messages_update_author" on public.messages;
create policy "messages_update_author" on public.messages
  for update using (
    exists (
      select 1
      from public.family_members fm
      where fm.id = public.messages."senderMemberId"
        and fm."userId" = public.famora_auth_uid()
        and fm.status = 'ACTIVE'
    )
  )
  with check (
    exists (
      select 1
      from public.family_members fm
      where fm.id = public.messages."senderMemberId"
        and fm."userId" = public.famora_auth_uid()
        and fm.status = 'ACTIVE'
    )
  );

drop policy if exists "messages_moderate_members" on public.message_reactions;
-- (reactions/read states are member-scoped self-policy, mirror of below.)

-- ---------------------------------------------------------------------------
-- 7. Content tables — active-member, family-scoped floor
-- ---------------------------------------------------------------------------
-- Side effects (polls, agenda, tasks, notebooks, files, announcements,
-- contacts, recipes, albums, memories, notifications, activity) use a single
-- generic pattern: only ACTIVE members of the owning family can read/write.

drop policy if exists "polls_select_members" on public.polls;
create policy "polls_select_members" on public.polls
  for select using (public.famora_is_active_member(public.polls."familyId"));

drop policy if exists "polls_insert_members" on public.polls;
create policy "polls_insert_members" on public.polls
  for insert with check (public.famora_is_active_member(public.polls."familyId"));

drop policy if exists "polls_update_members" on public.polls;
create policy "polls_update_members" on public.polls
  for update using (public.famora_is_active_member(public.polls."familyId"))
  with check (public.famora_is_active_member(public.polls."familyId"));

drop policy if exists "calendar_events_select_members" on public.calendar_events;
create policy "calendar_events_select_members" on public.calendar_events
  for select using (
    public.famora_is_active_member(public.calendar_events."familyId")
    and public.calendar_events."deletedAt" is null
  );

drop policy if exists "calendar_events_insert_members" on public.calendar_events;
create policy "calendar_events_insert_members" on public.calendar_events
  for insert with check (public.famora_is_active_member(public.calendar_events."familyId"));

drop policy if exists "calendar_events_update_members" on public.calendar_events;
create policy "calendar_events_update_members" on public.calendar_events
  for update using (public.famora_is_active_member(public.calendar_events."familyId"))
  with check (public.famora_is_active_member(public.calendar_events."familyId"));

drop policy if exists "tasks_select_members" on public.tasks;
create policy "tasks_select_members" on public.tasks
  for select using (
    public.famora_is_active_member(public.tasks."familyId")
    and public.tasks."deletedAt" is null
  );

drop policy if exists "tasks_insert_members" on public.tasks;
create policy "tasks_insert_members" on public.tasks
  for insert with check (public.famora_is_active_member(public.tasks."familyId"));

drop policy if exists "tasks_update_members" on public.tasks;
create policy "tasks_update_members" on public.tasks
  for update using (public.famora_is_active_member(public.tasks."familyId"))
  with check (public.famora_is_active_member(public.tasks."familyId"));

drop policy if exists "notebook_pages_select_members" on public.notebook_pages;
create policy "notebook_pages_select_members" on public.notebook_pages
  for select using (
    exists (
      select 1 from public.notebooks nb
      where nb.id = public.notebook_pages."notebookId"
        and nb."familyId" is not null
        and public.famora_is_active_member(nb."familyId")
    )
    or exists (
      select 1 from public.notebooks nb
      where nb.id = public.notebook_pages."notebookId"
        and nb."familyId" is null
        and nb."ownerId" = public.famora_auth_uid()
    )
  );

drop policy if exists "family_contacts_select_members" on public.family_contacts;
create policy "family_contacts_select_members" on public.family_contacts
  for select using (public.famora_is_active_member(public.family_contacts."familyId"));

drop policy if exists "family_contacts_insert_members" on public.family_contacts;
create policy "family_contacts_insert_members" on public.family_contacts
  for insert with check (public.famora_is_active_member(public.family_contacts."familyId"));

drop policy if exists "recipes_select_members" on public.recipes;
create policy "recipes_select_members" on public.recipes
  for select using (
    public.famora_is_active_member(public.recipes."familyId")
    and public.recipes."deletedAt" is null
  );

drop policy if exists "recipes_insert_members" on public.recipes;
create policy "recipes_insert_members" on public.recipes
  for insert with check (public.famora_is_active_member(public.recipes."familyId"));

drop policy if exists "memories_select_members" on public.memories;
create policy "memories_select_members" on public.memories
  for select using (
    public.famora_is_active_member(public.memories."familyId")
    and public.memories."deletedAt" is null
  );

drop policy if exists "memories_insert_members" on public.memories;
create policy "memories_insert_members" on public.memories
  for insert with check (public.famora_is_active_member(public.memories."familyId"));

drop policy if exists "announcements_select_members" on public.announcements;
create policy "announcements_select_members" on public.announcements
  for select using (
    public.famora_is_active_member(public.announcements."familyId")
    and public.announcements."deletedAt" is null
  );

drop policy if exists "announcements_insert_members" on public.announcements;
create policy "announcements_insert_members" on public.announcements
  for insert with check (public.famora_is_active_member(public.announcements."familyId"));

drop policy if exists "notifications_select_owner" on public.notifications;
create policy "notifications_select_owner" on public.notifications
  for select using (public.notifications."userId" = public.famora_auth_uid());

drop policy if exists "activity_events_select_members" on public.activity_events;
create policy "activity_events_select_members" on public.activity_events
  for select using (public.famora_is_active_member(public.activity_events."familyId"));

-- Audit logs: chiefs & Hidden Admin only (matches audit.read default set).
drop policy if exists "audit_logs_select_admins" on public.audit_logs;
create policy "audit_logs_select_admins" on public.audit_logs
  for select using (
    public.famora_has_internal_role(public.audit_logs."familyId", array['FAMILY_CHIEF','HIDDEN_ADMIN']::internal_role[])
  );

-- ---------------------------------------------------------------------------
-- 8. Storage buckets are enforced through Supabase Storage policies; the
-- family+user path scheme is documented in prisma/schema.prisma (FileBlob).
-- Update storage.objects policies in migration 0003_storage_policies.sql.
-- ---------------------------------------------------------------------------